# Site settings
title: Matt Wittmann
email: mcwitt@gmail.com
description: "Matt Wittmann"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty

kramdown:
    input: GFM
    hard_wrap: false
    smart_quotes: ["lsquo","rsquo","ldquo","rdquo"]
